meta:
  site_title: "Ami Miami- Calendar Test"
  site_subtitle: "Judaism in North Dade"
  site_language: "en"
  baseurl: /jekyll-calendar
#  absolute_baseurl: http://bludrop.github.io/jekyll-calendar/
#  domain: http://bludrop.github.io/jekyll-calendar/
  author:
    full_name: Brian Blumenthal
    short_name: bludrop
    email: brian@bludrop.com

pygments: true
markdown: rdiscount
permalink: pretty