meta:
  site_title: "Ami Miami- Calendar Test"
  site_subtitle: "Judaism in North Dade"
  site_language: "en"
  absolute_baseurl: http://bludrop.github.io/jekyll-serve
#  domain: seattlehacks.com
  author:
    full_name: Brian Blumenthal
    short_name: bludrop
    email: brian@bludrop.com

pygments: true
markdown: rdiscount
permalink: pretty